= standalone-datasource-parser image:https://travis-ci.org/daggerok/standalone-datasource-parser.svg?branch=master["Build Status", link="https://travis-ci.org/daggerok/standalone-datasource-parser"]

//tag::content[]
=== standalone-datasource-parser

Main goal of that project is provide some xml parsing functionality.
Needed for parsing JBOSS standalone.xml.
For example, when we need somehow get datasource configuration information from standalone.xml and open database connection.
To do so, we need few components:

. arguments-extension in case if client is terminal short-living application
. xml-parser extension to parse XML using XPath/XSLT/XQuery/XLink/XPointer (whatever you prefer) bu I will use Jackson XML functionality
. standalone-datasource-parser integration tests or simple acceptance test using main method run (tested with default standalone.xml from JBOSS EAP 6.4 / 7.1).
  As result, main goal and business value of it is: get datasource configuration from JBOSS EAP standalone.xml file

.using kotlin args-extension
[sources,bash]
----
java -jar target/*-all.jar --standalone-file=$(pwd)/standalone.xml
----

.getting standalone.xml (JBOSS EAP 6.4)
[sources,bash]
----
docker run --rm -d --name jboss daggerok/jboss:eap-6.4
docker cp jboss:/home/jboss-eap-6.4/jboss-eap-6.4/standalone/configuration/standalone.xml ./
docker rm -f -v jboss
docker run --rm -d --name jboss daggerok/jboss:eap-7.1
docker cp jboss:/home/jboss-eap-7.1/jboss-eap-7.1/standalone/configuration/standalone.xml ./standalone-7.1.xml
docker rm -f -v jboss
----

generated by link:https://github.com/daggerok/generator-daggerok-fatjar/[daggerok-fatjar] yeoman generator
//end::content[]
